name: AI Site Maintenance (manual)
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Manual workflow is wired correctly."
