name: AI Ops Issue to PR

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  issue_to_pr:
    if: contains(github.event.issue.labels.*.name, 'ai-change')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate patch from issue with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          set -e
          echo "Creating prompt..."
          cat > prompt.txt << 'EOF'
          You modify this repository according to the user request below.
          Return a SINGLE UNIFIED DIFF (git patch) against the repository root.
          - Keep changes small and safe.
          - Do not break the site build.
          - Prefer edits to existing files over creating new ones unless necessary.
          - Use UTF-8.
          REQUEST START
          EOF
          echo "${ISSUE_TITLE}" >> prompt.txt
          echo "" >> prompt.txt
          echo "${ISSUE_BODY}" >> prompt.txt
          echo "REQUEST END" >> prompt.txt

          echo "Calling OpenAI..."
          curl -sS https://api.openai.com/v1/responses \
            -H "Authorization: Bearer ${OPENAI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @- > response.json <<JSON
          {
            "model": "gpt-5-thinking",
            "input": "$(sed ':a;N;$!ba;s/\n/\\n/g' prompt.txt)",
            "temperature": 0.2
          }
          JSON

          node - <<'NODE'
          const fs = require('fs');
          try{
            const data = JSON.parse(fs.readFileSync('response.json','utf8'));
            const text = data.output_text || (data.content && data.content[0] && data.content[0].text) || '';
            fs.writeFileSync('ai.patch', text);
            if(!text.includes('--- ') || !text.includes('+++ ')) {
              console.log('No valid diff returned. Exiting without PR.');
              process.exit(0);
            }
          } catch(e) {
            console.error(e);
            process.exit(0);
          }
          NODE

          echo "Applying patch..."
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BR=ai/ops-${GITHUB_RUN_ID}
          git checkout -b "$BR"
          git apply --whitespace=fix ai.patch || { echo "Patch failed to apply"; exit 0; }
          git add -A
          git commit -m "AI Ops: ${ISSUE_TITLE}" || { echo "Nothing to commit"; exit 0; }
          echo "PR_BRANCH=$BR" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.PR_BRANCH != ''
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.PR_BRANCH }}
          title: AI Ops: ${{ github.event.issue.title }}
          body: |
            Change generated from issue #${{ github.event.issue.number }} (label: ai-change).

            Closes #${{ github.event.issue.number }}
          commit-message: AI Ops: ${{ github.event.issue.title }}
          base: main
